import Intro from '@/components/Intro'
import NavBar from '@/components/NavBar'
import { useSession } from "next-auth/react"
import Head from 'next/head'
import { useEffect } from 'react'


export default function Home() {

  const { data: session } = useSession()

  useEffect(() => {
    if(session) {
      Router.push('/frontend/dashboard')
    }
  }, [session])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className="w-full h-screen bg-gray-200  text-black">
        <Intro />
        <Intro />
        <Intro />
      </div>
    </>
  )
}
